# Build Settings
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
title: Choo.js
description: A multilingual full-stack web application toolkit, inspired by Ruby on Rails.
show_downloads: false
